- name: Add java 17 repo
  apt_repository:
    repo: 'ppa:linuxuprising/java'
    state: present

- name: Accept Java 17 License
  become: yes
  debconf: name='oracle-java17-installer' question='shared/accepted-oracle-license-v1-3' value='true' vtype='select'

- name: Install java 17
  apt:
    name: oracle-java17-installer
    update_cache: yes

- name: Set java 17 as default java
  apt:
    name: oracle-java17-set-default