- name: Create my user
  user: 
    name: mark
    state: present
    shell: /bin/bash

- name: Add ssh keys  
  authorized_key:
    user: mark
    state: present
    key: https://github.com/mflwr.keys