- name: Create my user
  user: 
    name: mark
    shell: /bin/bash
    groups:
      - sudo

- name: Add ssh keys  
  authorized_key:
    user: mark
    state: present
    key: https://github.com/mflwr.keys
