- name: Install docker prerequirements
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

- name: Add docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Passwordless sudo
  copy:
    dest: /etc/sudoers.d/passwordless
    content: "%sudo  ALL=(ALL) NOPASSWD: ALL"

- name: Add docker repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable

- name: Install docker
  apt:
    name: docker-ce
    cache_valid_time: 86400
    
- name: Add user to group docker
  user: 
    name: mark
    shell: /bin/bash
    groups:
      - docker
